### PR TITLE
Use rancher/yip v1.4.8

### LINKED ISSUE #1911: Switch yip to rancher/yip
As mudler/yip appears to be abandoned (too many `renovatebot` PRs unmerged), we should switch to [rancher/yip](https://github.com/rancher/yip) and take over maintenance.

### PR DESCRIPTION
**Pull request by frelon**
This includes the update to vfs4.

Fixes #1911, #1913

### CODE REVIEW

**Review by davidcassany — APPROVED** [review]
LGTM

**Comment by kkaempf** [comment]
This shouldn't have been merged.

It has a misleading title. 😞

**Comment by frelon** [comment]
> This shouldn't have been merged.
> 
> 
> 
> It has a misleading title. 😞 

I'm confused, what is misleading about the title?

**Comment by frelon** [comment]
> > > This shouldn't have been merged.
> 
> > > It has a misleading title. 😞
> 
> > 
> 
> > I'm confused, what is misleading about the title?
> 
> 
> 
> The title just references one change ("Use rancher/yip v1.4.8") but the PR changes two things (update of yip, change to rancher/yip). This should've been two separate PRs imho.

Technically the title references both changes..

I agree it could have been two commits, but spending time splitting these relatively small bumps into several feels nitpicky to me (especially if the commits are later squashed...).

**Pull request merged**
