### PR TITLE
bump teal-x86_64.yaml base os

### PR DESCRIPTION
**Pull request by Itxaka**
Signed-off-by: Itxaka <igarcia@suse.com>

### CODE REVIEW

**Review by davidcassany — COMMENTED** [review]
Shouldn't we also bump the builder to leap 15.4? I know it is unlikely to make any difference, but even if it is just for consistency

**Comment by Itxaka** [comment]
yep, sorry was too eager and added the bump and missed bumping cos, bumping arm64, too images etc...

Althougth as far as I can remember I tried to bump it some time ago and failed miserably.

**Comment by davidcassany** [comment]
Weird, looks like we are not passing the flavor to the docker builds. Orange, blue and green are all attempting to build with teal values. This should have not been altered in this PR, feels like an unrelated issue.

**Comment by Itxaka** [comment]
yeah, docker builds are totally broken, not sure if we should just disable them like they were just a couple of months ago.

**Review by davidcassany — APPROVED** [review]
Looks good to me

A bit concerned about the failures on the bios installer tests 🤔 I doubt it has direct relation with the changes here though

Given the vast majority of tests are passing I think can disable docker flavors builds and probably focus on failing teal tests in follow up PRs

**Comment by Itxaka** [comment]
> A bit concerned about the failures on the bios installer tests thinking I doubt it has direct relation with the changes here though

yup, gonna wait until is re-run, according to the logs, there was a disconnection so it could not copy the proper files into the VM so it failed.

Gotta wait for a while thought, its run on macos workers are we have none available right now ¬_¬

**Comment by Itxaka** [comment]
ah, I see!

Its just that due to https://github.com/rancher/elemental-cli/pull/287 we now start the custom files from 90, and before we just copied the cloud config files into 99-custom.yaml, so in the test we check for that specific file, thus it wont work.

Will merge this and send a PR to fix the tests.

**Comment by davidcassany** [comment]
> Its just that due to [rancher/elemental-cli#287](https://github.com/rancher/elemental-cli/pull/287) we now start the custom files from 90, and before we just copied the cloud config files into 99-custom.yaml, so in the test we check for that specific file, thus it wont work.

Good catch! Damn, we are overlooking this repository... I wish we had a cleaner relation between `elemental` and  `elemental-toolkit` repos...

**Comment by Itxaka** [comment]
To be honest, on testing just getting transient/new files by specific name is pretty bad as its error prone. We should not get that file directly but just look at the files in /oem and check all of them instead :D

Although a cross project testing like zuul does would be really nice in this case :D

**Pull request merged**
