### PR TITLE
Revert "Revert manifest until new elemental is pushed"

### PR DESCRIPTION
**Pull request by Itxaka**
Reverts rancher/elemental-toolkit#1513

### CODE REVIEW

**Comment by Itxaka** [comment]
Now that the new elemental has been pushed and will be consumed on the iso/raw disk steps, we can update the manifest.yaml

**Comment by Itxaka** [comment]
oh yeah, this wont run any jobs because the manifest.yaml is not included in the files to trigger the jobs....

**Review by frelon — APPROVED** [review]

**Comment by davidcassany** [comment]
Ouch, I was about to say this will conflict with #1501... 😅 as I had to include that in there.

Also I am afraid with the current steps order in build-iso job, the new elemental won't be used. In #1501 I had to revert the revert of `make ci_deps` steps.

**Comment by Itxaka** [comment]
yes, new elemental wont be used and we have to choose between using the new elmental or fully breaking arm64 (again lol): https://github.com/rancher/elemental-toolkit/issues/1515

**Pull request merged**
