### PR TITLE
Add sgdisk to the inmutable-rootfs module setup

### LINKED ISSUE #1632: Failed analyzing disk: exec: "sgdisk": executable file not found in $PATH
This happens on the test-raw-disk, seems like when elemental run-stage goes to create the partitions, it cannot find the sgdisk command.

Maybe it needs to be added to the inmutable-rootfs module setup so its available early in the boot process as other disk utils

### PR DESCRIPTION
**Pull request by Itxaka**
Fixes #1632

Signed-off-by: Itxaka <igarcia@suse.com>

### CODE REVIEW

**Review by davidcassany — APPROVED** [review]
Oh my bad... yes sgdisk is used to expand the disk on gpt partition tables as parted is missing such a feature.

**Comment by davidcassany** [comment]
Up to my understanding this will not hit `system`/cos unless you bump the initrd package too.

**Comment by Itxaka** [comment]
I'm just trying to understand why it started failing suddenly out of nowhere. It's very confusing.

**Review by fgiudici — APPROVED** [review]

**Comment by fgiudici** [comment]
Related to https://github.com/rancher/elemental-toolkit/pull/1631

**Comment by Itxaka** [comment]
> Related to https://github.com/rancher/elemental-toolkit/pull/1631

Well I hope so! 🤣

**Comment by fgiudici** [comment]
> > Related to #1631
> 
> Well I hope so! rofl

 it was just to put a link for (self-)navigation through issues and associated PRs 🤣

**Comment by Itxaka** [comment]
> > > Related to #1631
> > 
> > 
> > Well I hope so! rofl
> 
> it was just to put a link for (self-)navigation through issues and associated PRs rofl

I mostly meant that the link its worng as its pointing to itself :)

Sorry, still sleepy, did not finish the comment lmao. I put the correct Fixes stanza in the first comment :+1:

**Comment by Itxaka** [comment]
> I'm just trying to understand why it started failing suddenly out of nowhere. It's very confusing.

Blerg, now I see it, it was dropped by mistake 2 PRs ago but then on my EFI PR initrd was bumped. So thats when the errors appear. Ok, clear now, bumping initrd.

**Comment by fgiudici** [comment]
> I mostly meant that the link its worng as its pointing to itself :)
> 
> Sorry, still sleepy, did not finish the comment lmao. I put the correct Fixes stanza in the first comment +1

🤦🏼 I thought I put a link to the issue... the one still sleepy it's me 😪  🤣

**Comment by davidcassany** [comment]
> I'm just trying to understand why it started failing suddenly out of nowhere. It's very confusing.

I am the one to blame here, I removed the sgdisk from initrd while cleaning up few packages mostly due to bootloader changes. I though it was a leftover. In fact, sgdisk should not be used, as we relay on `parted`, however then I found this (I had completely forgot it): https://github.com/rancher/elemental-cli/blob/b918db3867add2cd4a2ea0cff748638b04556fdf/pkg/partitioner/disk.go#L125-L143

**Comment by Itxaka** [comment]
> > I'm just trying to understand why it started failing suddenly out of nowhere. It's very confusing.
> 
> I am the one to blame here, I removed the sgdisk from initrd while cleaning up few packages mostly due to bootloader changes. I though it was a leftover. In fact, sgdisk should not be used, as we relay on `parted`, however then I found this (I had completely forgot it): [rancher/elemental-cli@`b918db3`/pkg/partitioner/disk.go#L125-L143](https://github.com/rancher/elemental-cli/blob/b918db3867add2cd4a2ea0cff748638b04556fdf/pkg/partitioner/disk.go#L125-L143)


Yeah I finally found it. My confusion was that I wrongly did a git history and thougth that the sgdisk was not part of the initrd for a long long time, so I was very confused on why would it happen now when we bumped the initrd several times. Until I found out that it was a very recent slip and then it make sense :D

**Comment by kkaempf** [comment]
This is important information which isn't captured in the PR :-(

We should add a comment in [module-setup.sh](https://github.com/rancher/elemental-toolkit/blob/915dba4bd59ba3500eb4bae12868e139589de485/packages/immutable-rootfs/30cos-immutable-rootfs/module-setup.sh#L31) to notice that `sgdisk` can be dropped once `parted` has catched up.

**Pull request merged**
