### PR TITLE
[tests] Fix custom config file name

### PR DESCRIPTION
**Pull request by Itxaka**
Signed-off-by: Itxaka <igarcia@suse.com>

### CODE REVIEW

**Comment by kkaempf** [comment]
Which problem does this fix ?

**Comment by Itxaka** [comment]
> Which problem does this fix ?

A test failing becuase naming has changed under elemental-cli.

**Review by kkaempf — APPROVED** [review]
Who am I to object ?

**Comment by Itxaka** [comment]
efi tests are now passing, merging already

**Pull request merged**
